<a href="https://colab.research.google.com/github/SidharthBhakth/pyTorch-60-mins-blitz/blob/master/01_What_is_pyTorch%3F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors

In [1]:
from __future__ import print_function
import torch

In [2]:
# Construct a 5x3 matrix, uninitialized
x = torch.empty(5, 3)
print(x)

tensor([[4.4900e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.5186e-36]])


In [3]:
# Construct a randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.4038, 0.4871, 0.0892],
        [0.4928, 0.3581, 0.5046],
        [0.0482, 0.3103, 0.4999],
        [0.3254, 0.4339, 0.3189],
        [0.7022, 0.6081, 0.5251]])


In [4]:
# Construct a matrix filled with zeros and dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# Create a tensor based on an existing tensor
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)        # override dtype
print(x)                                          # result has the same size
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0530,  1.2153,  0.5681],
        [ 0.6947, -1.1578,  1.2029],
        [-1.2398, -1.0194, -0.7355],
        [-0.9017, -0.7235, -2.5615],
        [-0.6968,  0.1773, -0.5989]])
torch.Size([5, 3])


## Operations

**Addition**

In [7]:
# syntax 1
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.5622,  1.4863,  1.3304],
        [ 0.8800, -0.5047,  1.2384],
        [-0.9962, -0.8095, -0.3162],
        [-0.0862,  0.1459, -2.0180],
        [ 0.0934,  0.4738, -0.4814]])


In [8]:
# syntax 2
print(torch.add(x, y))

tensor([[ 1.5622,  1.4863,  1.3304],
        [ 0.8800, -0.5047,  1.2384],
        [-0.9962, -0.8095, -0.3162],
        [-0.0862,  0.1459, -2.0180],
        [ 0.0934,  0.4738, -0.4814]])


In [9]:
# providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.5622,  1.4863,  1.3304],
        [ 0.8800, -0.5047,  1.2384],
        [-0.9962, -0.8095, -0.3162],
        [-0.0862,  0.1459, -2.0180],
        [ 0.0934,  0.4738, -0.4814]])


In [10]:
# in=place addition
y.add_(x)
print(y)

tensor([[ 1.5622,  1.4863,  1.3304],
        [ 0.8800, -0.5047,  1.2384],
        [-0.9962, -0.8095, -0.3162],
        [-0.0862,  0.1459, -2.0180],
        [ 0.0934,  0.4738, -0.4814]])


In [11]:
print(y[:, 1])

tensor([ 1.4863, -0.5047, -0.8095,  0.1459,  0.4738])


**Resizing**

In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)     # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
# If you have a one element tensor, use .item() to get the value as a Python scalar
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.7007])
-0.7006537914276123


## Converting a Torch Tensor to a NumPy Array


In [14]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [15]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor

In [16]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

In [17]:
if torch.cuda.is_available():
  device = torch.device("cuda")             # a CUDA device object
  y = torch.ones_like(x, device=device)     # directly create a tensor on GPU
  x = x.to(device)                          # alternatively
  z = x + y

  print(z)
  print(z.to("cpu", dtype=torch.double))

tensor([0.2993], device='cuda:0')
tensor([0.2993], dtype=torch.float64)
